version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
      - pip install databricks-cli

  pre_build:
    commands:
      - echo "Setting up Databricks authentication"
      - export DATABRICKS_HOST="https://dbc-19dd5697-db5b.cloud.databricks.com"
      - export DATABRICKS_TOKEN="dapied254a643e30617a3526aa324911c84a"
      - databricks auth login --host $DATABRICKS_HOST --token $DATABRICKS_TOKEN

  build:
    commands:
      - echo "Deploying Databricks Bundle"
      - databricks bundle deploy --config databricks.yml

  post_build:
    commands:
      - echo "Triggering job execution"
      - databricks jobs run --json "{ \"task_key\": \"run-script-dev\" }"

artifacts:
  files:
    - databricks.yml
    - src/sample_script.py
