version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install --upgrade pip
      - pip install databricks-cli

  pre_build:
    commands:
      - echo "Configuring Databricks CLI authentication"
      - databricks configure --host https://dbc-19dd5697-db5b.cloud.databricks.com --token dapied254a643e30617a3526aa324911c84a

  build:
    commands:
      - echo "Deploying Databricks Asset Bundle"
      - databricks asset-bundle deploy --bundle-config databricks.yml

  post_build:
    commands:
      - echo "Triggering job execution"
      - databricks jobs run-now --task-name run-script

artifacts:
  files:
    - databricks.yml
    - src/sample_script.py
